dist: xenial
language: csharp
mono: none
dotnet: 2.2.104
env:
  - PATH=$PATH:$HOME/.dotnet/tools
script:
  - ./build.sh
 # - dotnet tool install -g Wyam.Tool
 # - wyam build
# install:
# - dotnet tool install -g Wyam.Tool
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: _site
#   target_branch: master
#   on:
#     branch: source